version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/password-generator
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
                  python3 -m venv venv
                  . venv/bin/activate
workflows:
  build:
    jobs:
      - build