version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/password-generator
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements.txt
      #3 Run coding convention software plus tester.
      - run:
          name: run tests
          command: |
                  . venv/bin/activate
                  flake8 --exclude=venv* --statistics
                  # pytest -v --cov=calculator
                  pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results        
workflows:
    jobs:
      - build
