version: 2.1
jobs:
  build-circleci-first-time:
    docker:
      - image: cimg/python:3.12    
    working_directory: ~/password-generator
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
workflows:
  build-circleci-first-time:
    jobs:
      - build